In [1]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
#Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'15',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

In [2]:
type(data)

dict

In [3]:
import pandas as pd


#This allows you to see all the columns, not just like 15
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
#This normalizes the data and makes it all pretty in a dataframe

df = pd.json_normalize(data['data'])
df['timestamp'] = pd.to_datetime('now')
df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,10846,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.964415e+07,1.964415e+07,False,NaN,1,NaN,NaN,None,2024-03-04T06:22:00.000Z,63575.995748,3.496961e+10,67.7636,0.110749,2.697468,23.432304,47.438013,47.381635,51.819788,1.248896e+12,52.3425,1.335096e+12,None,2024-03-04T06:22:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
1,1027,Ethereum,ETH,ethereum,8492,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.201331e+08,1.201331e+08,True,NaN,2,NaN,NaN,None,2024-03-04T06:22:00.000Z,3469.484806,1.612984e+10,47.8015,-0.098754,1.591453,11.849702,49.500415,55.092413,55.144808,4.168001e+11,17.4743,4.168001e+11,None,2024-03-04T06:22:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
2,825,Tether USDt,USDT,tether,76728,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,9.951523e+10,1.028001e+11,True,NaN,3,NaN,NaN,None,2024-03-04T06:21:00.000Z,1.000504,8.074829e+10,30.1344,-0.004250,0.001435,0.048328,0.072663,-0.020728,0.050199,9.956539e+10,4.1743,1.028519e+11,None,2024-03-04T06:21:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2024-03-04 11:53:43.433319
3,1839,BNB,BNB,bnb,2081,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.495417e+08,1.495417e+08,False,NaN,4,NaN,NaN,None,2024-03-04T06:21:00.000Z,414.609738,1.891551e+09,35.6388,-0.133703,1.139717,7.544943,36.709566,28.891296,78.643804,6.200144e+10,2.6000,6.200144e+10,None,2024-03-04T06:21:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
4,5426,Solana,SOL,solana,630,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.429432e+08,5.710439e+08,True,NaN,5,NaN,NaN,None,2024-03-04T06:22:00.000Z,129.069012,3.270762e+09,40.3326,-0.109744,-0.006669,24.385938,29.425855,28.077030,114.057459,5.717024e+10,2.3961,7.370407e+10,None,2024-03-04T06:22:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
5,52,XRP,XRP,xrp,1237,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, arr...",1.000000e+11,5.466403e+10,9.998785e+10,False,NaN,6,NaN,NaN,None,2024-03-04T06:22:00.000Z,0.624696,2.211938e+09,-1.6076,-0.785606,-0.772643,15.745736,23.157795,7.610020,0.796609,3.414839e+10,1.4312,6.246958e+10,None,2024-03-04T06:22:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
6,3408,USDC,USDC,usd-coin,17001,2018-10-08T00:00:00.000Z,"[medium-of-exchange, stablecoin, asset-backed-...",NaN,2.895219e+10,2.895219e+10,False,NaN,7,NaN,NaN,None,2024-03-04T06:22:00.000Z,0.999907,6.841049e+09,31.6763,-0.001804,0.027639,-0.000182,-0.039227,-0.023550,-0.000372,2.894950e+10,1.2133,2.894950e+10,None,2024-03-04T06:22:00.000Z,1027.0,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2024-03-04 11:53:43.433319
7,2010,Cardano,ADA,cardano,1086,2017-10-01T00:00:00.000Z,"[dpos, pos, platform, research, smart-contract...",4.500000e+10,3.548478e+10,3.667143e+10,False,NaN,8,NaN,NaN,None,2024-03-04T06:21:00.000Z,0.779533,1.175344e+09,24.5981,4.603842,6.769875,33.071033,50.476707,38.462100,92.556782,2.766154e+10,1.1600,3.507896e+10,None,2024-03-04T06:21:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
8,74,Dogecoin,DOGE,dogecoin,901,2013-12-15T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, me...",NaN,1.433239e+11,1.433239e+11,True,NaN,9,NaN,NaN,None,2024-03-04T06:22:00.000Z,0.162487,4.815500e+09,66.4968,2.536448,17.131588,89.715892,105.204638,97.157859,80.250704,2.328821e+10,0.9760,2.328821e+10,None,2024-03-04T06:22:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
9,5805,Avalanche,AVAX,avalanche,674,2020-07-13T00:00:00.000Z,"[defi, smart-contracts, three-arrows-capital-p...",7.200000e+08,3.772527e+08,4.359423e+08,False,NaN,10,NaN,NaN,None,2024-03-04T06:21:00.000Z,42.317683,5.816149e+08,-4.7999,-0.005382,-2.042163,13.888456,16.961279,14.313756,85.882540,1.596446e+10,0.6695,3.046873e+10,None,2024-03-04T06:21:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
10,5994,Shiba Inu,SHIB,shiba-inu,749,2020-08-01T00:00:00.000Z,"[memes, ethereum-ecosystem, doggone-doggerel]",NaN,5.892894e+14,5.895341e+14,False,NaN,11,NaN,NaN,None,2024-03-04T06:21:00.000Z,0.000025,3.528777e+09,-30.8441,7.621271,18.745407,161.474628,176.422326,160.644157,175.332554,1.482783e+10,0.6218,1.483398e+10,None,2024-03-04T06:21:00.000Z,1027.0,Ethereum,ETH,ethereum,0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce,2024-03-04 11:53:43.433319
11,6636,Polkadot,DOT,polkadot-new,697,2020-08-19T00:00:00.000Z,"[substrate, polkadot, binance-chain, polkadot-...",NaN,1.285541e+09,1.417802e+09,True,NaN,12,NaN,NaN,None,2024-03-04T06:21:00.000Z,9.814043,7.167697e+08,42.9406,0.845160,7.081559,25.449918,42.016993,27.336733,73.296663,1.261636e+10,0.5291,1.391437e+10,None,2024-03-04T06:21:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
12,1958,TRON,TRX,tron,937,2017-09-13T00:00:00.000Z,"[media, payments, tron-ecosystem, layer-1, dwf...",NaN,8.795383e+10,8.795388e+10,True,NaN,13,7.165966e+10,1.002298e+10,None,2024-03-04T06:21:00.000Z,0.139869,3.331835e+08,22.3017,0.068266,-0.831018,1.477017,20.434042,28.906110,35.088042,1.230203e+10,0.5159,1.230204e+10,None,2024-03-04T06:21:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319
13,1975,Chainlink,LINK,chainlink,1664,2017-09-20T00:00:00.000Z,"[platform, defi, oracles, smart-contracts, sub...",1.000000e+09,5.871000e+08,1.000000e+09,False,NaN,14,NaN,NaN,None,2024-03-04T06:21:00.000Z,20.265071,6.857405e+08,-1.3665,-0.072869,-3.384708,9.224549,14.389612,40.549875,30.351812,1.189762e+10,0.4989,2.026507e+10,None,2024-03-04T06:21:00.000Z,1027.0,Ethereum,ETH,ethereum,0x514910771af9ca656af840dff83e8264ecf986ca,2024-03-04 11:53:43.433319
14,3890,Polygon,MATIC,polygon,1296,2019-04-28T00:00:00.000Z,"[pos, platform, enterprise-solutions, zero-kno...",1.000000e+10,9.899143e+09,1.000000e+10,False,NaN,15,NaN,NaN,None,2024-03-04T06:21:00.000Z,1.083639,7.707488e+08,2.1940,-0.806354,-0.852057,8.625011,36.191797,25.116191,34.763370,1.072710e+10,0.4497,1.083639e+10,None,2024-03-04T06:21:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-04 11:53:43.433319

In [6]:
def api_runner():
    global df
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
    #Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    parameters = {
      'start':'1',
      'limit':'15',
      'convert':'USD'
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
    }

    session = Session()
    session.headers.update(headers)

    try:
      response = session.get(url, params=parameters)
      data = json.loads(response.text)
      #print(data)
    except (ConnectionError, Timeout, TooManyRedirects) as e:
      print(e)

#NOTE:
# I had to go in and put "jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10"
# Into the Anaconda Prompt to change this to allow to pull data
    
    # Use this if you just want to keep it in a dataframe
    df2 = pd.json_normalize(data['data'])
    df2['Timestamp'] = pd.to_datetime('now')
    df = df.append(df2)

In [8]:
import os 
import pandas as pd  # Import pandas library
from time import sleep

# Initialize an empty DataFrame before the loop
df = pd.DataFrame()

for i in range(333):
    # Assuming api_runner() returns data in DataFrame format
    data = api_runner()
    
    df2 = pd.json_normalize(data['data'])
    df2['Timestamp'] = pd.to_datetime('now')
    
    # Append df2 to df
    df = df.append(df2, ignore_index=True)  
    
    print('API Runner completed')
    sleep(60)  # sleep for 1 minute

df.to_csv('output.csv', index=False)


exit()

AttributeError: 'DataFrame' object has no attribute 'append'

In [9]:
df

Empty DataFrame
Columns: []
Index: []

In [10]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [11]:
df

Empty DataFrame
Columns: []
Index: []

In [12]:
df3 = df.groupby('name', sort=False)[['quote.USD.percent_change_1h','quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d']].mean()
df3

KeyError: 'name'

In [ ]:
df4 = df3.stack()
df4

In [13]:
type(df4)

NameError: name 'df4' is not defined

In [14]:
df5 = df4.to_frame(name='values')
df5

NameError: name 'df4' is not defined

In [ ]:
df5.count()

In [15]:
index = pd.Index(range(90))
df6 = df5.set_index(index)
df6

NameError: name 'df5' is not defined

In [ ]:
df7 = df6.rename(columns={'level_1': 'percent_change'})
df7

In [ ]:
df7['percent_change'] = df7['percent_change'].replace(['quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d'],['24h','7d','30d','60d','90d'])
df7

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
sns.catplot(x='percent_change', y='values', hue='name', data=df7, kind='point')

In [ ]:
df10 = df[['name','quote.USD.price','timestamp']]
df10 = df10.query("name == 'Bitcoin'")
df10

In [ ]:
sns.set_theme(style="darkgrid")

sns.lineplot(x='timestamp', y='quote.USD.price', data = df10)